elasticsearch:
  image: elasticsearch:1.6
  ports:
    - "9200:9200"
logstash:
  image: logstash:chop
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
  command: logstash -v -f /etc/logstash/conf.d/logstash.conf
kibana4:
  image: kibana:4
  ports:
    - "5601:5601"
  links:
    - elasticsearch
