elasticsearch:
  image: elasticsearch:1.5
  ports:
    - "9200:9200"
logstash:
  image: logstash:1.5
  volumes:
    - logstash-conf:/etc/logstash/conf.d
  ports:
    - "5000:5000"  
  links:
    - elasticsearch
  command: logstash -v -f /etc/logstash/conf.d/logstash.conf
kibana3:
  image: deviantony/elk-kibana:kibana3
  ports:
    - "8080:80"
  links:
    - elasticsearch
kibana4:
  image: deviantony/elk-kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
